## steps to update the GCP storage bucket social_app_v2 with latest build
steps:
  - name: "node"
    entrypoint: "yarn"
    args: ["install"] #installing dependencies

  - name: "node"
    entrypoint: "yarn"
    args: ["build"] #building the react app
    env:
      [
        "NODE_PATH=./src",
        "GENERATE_SOURCEMAP=true",
        "NODE_OPTIONS=--openssl-legacy-provider",
      ]

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "build", "gs://social_app_v2/"] # syncing the latest build with storage bucket

  - name: gcr.io/cloud-builders/gsutil # setting the entry point "index.html"
    args:
      [
        "-m",
        "web",
        "set",
        "-m",
        "index.html",
        "-e",
        "index.html",
        "gs://social_app_v2/",
      ]

  - name: gcr.io/cloud-builders/gsutil
    args:
      [
        "setmeta",
        "-h",
        "Cache-Control:no-cache",
        "gs://social_app_v2/index.html",
      ]

timeout: "2400s"
