## steps to update the GCP storage bucket social_app_v2_dev with latest build
steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install'] #installing dependencies

  - name: "gcr.io/cloud-builders/yarn"
    args: ["build"] #building the react app
    env: ["NODE_PATH=./src", "GENERATE_SOURCEMAP=true"]

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "build", "gs://social_app_v2_dev/"] # syncing the latest build with storage bucket

  - name: gcr.io/cloud-builders/gsutil # setting the entry point "index.html"
    args:
      [
        "-m",
        "web",
        "set",
        "-m",
        "index.html",
        "-e",
        "index.html",
        "gs://social_app_v2_dev/",
      ]

  - name: gcr.io/cloud-builders/gsutil
    args:
      [
        'setmeta',
        '-h',
        'Cache-Control:no-cache',
        'gs://social_app_v2_dev/index.html',
      ]

timeout: "600s"

