name: Firebase Deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: '1//0gvPpoArPAX6RCgYIARAAGBASNwF-L9Ir1nVUu8nwzS56J1Xu-9TIJWGk5OT36yFDSi1LeExWrjwSe9VVECKaDIJzF7DCYnTKgb8'
